#!/bin/bash

# MusicMu Serverless - Complete Deployment Script
# This script deploys both backend and frontend to Vercel in the correct order

set -e

echo "🚀 MusicMu Serverless Deployment"
echo "================================"
echo ""

# Check if vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Install with: npm install -g vercel"
    exit 1
fi

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Step 1: Deploy Backend
echo "📦 Step 1: Deploying Backend..."
cd backend

# Deploy to production
echo "   Running: vercel --prod"
DEPLOY_OUTPUT=$(vercel --prod 2>&1)
echo "$DEPLOY_OUTPUT"

# Extract backend URL from output
BACKEND_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'https://[^[:space:]]*vercel\.app' | head -1)

if [ -z "$BACKEND_URL" ]; then
    echo "❌ Failed to get backend URL from deployment"
    echo "Please check Vercel dashboard for backend URL"
    exit 1
fi

echo ""
echo "✅ Backend deployed successfully!"
echo "   URL: $BACKEND_URL"
echo ""

# Step 2: Test Backend
echo "🧪 Step 2: Testing Backend..."
sleep 3  # Wait for deployment to propagate

HEALTH_CHECK=$(curl -s "$BACKEND_URL/api/health" || echo "failed")
if echo "$HEALTH_CHECK" | grep -q "ok"; then
    echo "✅ Backend health check passed"
else
    echo "⚠️  Backend health check failed, but continuing..."
    echo "   Response: $HEALTH_CHECK"
fi
echo ""

# Step 3: Update Frontend Configuration
echo "🔧 Step 3: Updating Frontend Configuration..."
cd ../frontend

# Update .env.production
cat > .env.production << EOF
# MusicMu Serverless Frontend - Production Environment Variables
# Auto-generated by deploy-all.sh

# Backend API URL (from deployment)
VITE_API_URL=$BACKEND_URL

# App Configuration
VITE_APP_NAME=MusicMu
VITE_APP_VERSION=1.0.0
EOF

echo "✅ Frontend configuration updated"
echo "   VITE_API_URL=$BACKEND_URL"
echo ""

# Step 4: Deploy Frontend
echo "📦 Step 4: Deploying Frontend..."
FRONTEND_OUTPUT=$(vercel --prod 2>&1)
echo "$FRONTEND_OUTPUT"

FRONTEND_URL=$(echo "$FRONTEND_OUTPUT" | grep -o 'https://[^[:space:]]*vercel\.app' | head -1)

echo ""
echo "✅ Frontend deployed successfully!"
if [ -n "$FRONTEND_URL" ]; then
    echo "   URL: $FRONTEND_URL"
fi
echo ""

# Summary
echo "🎉 Deployment Complete!"
echo "======================="
echo ""
echo "Backend:  $BACKEND_URL"
if [ -n "$FRONTEND_URL" ]; then
    echo "Frontend: $FRONTEND_URL"
else
    echo "Frontend: Check Vercel dashboard for URL"
fi
echo ""
echo "📝 Next Steps:"
echo "1. Test backend: curl $BACKEND_URL/api/health"
if [ -n "$FRONTEND_URL" ]; then
    echo "2. Open frontend: $FRONTEND_URL"
fi
echo "3. Check Vercel dashboard for logs and domains"
echo ""
